"""Render a top-level SUMMARY.md from per-benchmark SUMMARY.md files.

Walks ``results/<benchmark>/SUMMARY.md``, prepends a TOC and a one-paragraph
description per benchmark, and writes ``results/SUMMARY.md``.

Usage:
    python -m scripts.render_summary --results results --out results/SUMMARY.md
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

log = logging.getLogger(__name__)

# Per-benchmark preamble, kept short (1-2 sentences each).
BENCHMARK_DESCRIPTIONS: dict[str, str] = {
    "ablation": "Ablation studies of VEGA and Recurrent Residual — each row reports the validation-loss "
                "delta from removing one design component (variance regularizer, multi-scale decay, "
                "or depth biases).",
    "depth_needle": "Per-mode validation loss and passkey-retrieval accuracy on the synthetic "
                    "depth-needle task (causal copy of a hidden passkey at varying depths).",
    "depth_preservation": "Depth Preservation Score (DPS) and Gradient Preservation Score (GPS) probed "
                          "on untrained models, one value per layer. The DRI / GPI columns are the "
                          "first-half means of these per-layer values.",
    "inference_memory": "Peak VRAM, p99 latency, and throughput for forward-only profiling across "
                        "(mode, depth) pairs.",
    "iso_flop": "Wide-shallow (6 × 1024) vs narrow-deep (24 × 512) variants of each mode at matched "
                "parameter count.  Compares the val_loss each shape achieves.",
    "lm_quality": "Validation loss, perplexity, throughput, peak memory, and parameter count for "
                  "the per-mode language-model quality benchmark on wikitext-103.",
    "natural_niah": "Natural-text needle-in-a-haystack: each row reports passkey retrieval success "
                    "from a model loaded with a checkpoint produced by `lm_quality`.",
    "scaling_efficiency": "Validation loss vs parameter count at multiple (d_model, num_layers) "
                          "sweep points — the Pareto curve per mode.",
}


def render(results_dir: Path, out_path: Path) -> int:
    """Walk results/<benchmark>/SUMMARY.md and concatenate into a top-level summary.

    Returns the number of benchmark summaries included (0 on failure).
    """
    if not results_dir.is_dir():
        log.error("Results directory does not exist: %s", results_dir)
        return 0
    body = ["# Project Summary", ""]
    body.append("This document aggregates per-benchmark summary tables. Each table is generated by "
                "`scripts/tables/<name>_table.py` from a per-benchmark CSV produced by "
                "`scripts/ingest/collect.py`.")
    body.append("")
    body.append("To regenerate this file (and all per-benchmark summaries and plots) from a Modal "
                "artifact root, run `make report` (see the top-level Makefile).")
    body.append("")

    # TOC.
    body.append("## Table of Contents")
    body.append("")
    summaries: list[tuple[str, Path]] = []
    for child in sorted(results_dir.iterdir()):
        if not child.is_dir():
            continue
        summary = child / "SUMMARY.md"
        if summary.is_file():
            summaries.append((child.name, summary))
            body.append(f"- [`{child.name}`](#{child.name})")
    body.append("")

    if not summaries:
        log.warning("No per-benchmark SUMMARY.md files found under %s", results_dir)
        out_path.write_text("\n".join(body), encoding="utf-8")
        return 0

    # Per-benchmark sections.
    for benchmark, summary_path in summaries:
        description = BENCHMARK_DESCRIPTIONS.get(benchmark)
        body.append(f"## {benchmark}")
        body.append("")
        if description:
            body.append(description)
            body.append("")
        # Append the contents of the per-benchmark SUMMARY.md, skipping its H1.
        text = summary_path.read_text(encoding="utf-8")
        lines = text.splitlines()
        # Drop the leading H1.
        if lines and lines[0].startswith("# "):
            lines = lines[1:]
        # Also drop a leading blank.
        while lines and not lines[0].strip():
            lines.pop(0)
        body.extend(lines)
        body.append("")

    out_path.write_text("\n".join(body), encoding="utf-8")
    return len(summaries)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--results", type=Path, default=Path("results"), help="Per-benchmark results root")
    parser.add_argument("--out", type=Path, default=Path("results") / "SUMMARY.md", help="Output summary file")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    n = render(args.results, args.out)
    if n == 0:
        log.error("No per-benchmark summaries found.")
        return 1
    log.info("Wrote %s (%d benchmarks)", args.out, n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
