"""Ablation summary table: per-ablation-variant deltas vs full mode.

Reads ``results/aggregate/ablation_summary.csv`` and emits
``results/ablation/SUMMARY.md``.

The 3 ablation variants are:
  * vega_no_var_reg       -> Δ vs vega
  * vega_no_multiscale    -> Δ vs vega
  * rr_no_depth_biases    -> Δ vs recurrent_residual

For each variant, we report the mean val_loss and val_ppl across runs, plus
the Δ vs the corresponding full mode.

Usage:
    python -m scripts.tables.ablation_table \\
        --csv results/aggregate/ablation_summary.csv \\
        --steps-csv results/aggregate/ablation_steps.csv \\
        --out results/ablation/SUMMARY.md
"""

from __future__ import annotations

import argparse
import logging
import math
import sys
from pathlib import Path

import pandas as pd

from scripts.tables.format import (
    apply_bold,
    bold_winner,
    write_markdown_table,
)

log = logging.getLogger(__name__)

# Mapping: ablation_variant -> base_mode (the full mode to compare against)
VARIANT_TO_BASE = {
    "vega_no_var_reg": "vega",
    "vega_no_multiscale": "vega",
    "rr_no_depth_biases": "recurrent_residual",
}


def _to_ppl(loss: float | None) -> float | None:
    if loss is None or pd.isna(loss):
        return None
    return round(math.exp(min(float(loss), 20.0)), 2)


def build_rows(df: pd.DataFrame, steps: pd.DataFrame | None) -> list[dict]:
    if df.empty:
        return []
    if "val_loss" not in (df.columns if steps is None else steps.columns) and steps is not None:
        # We need steps to compute val_loss.
        pass
    # Aggregate per mode: mean across runs.
    if steps is not None and not steps.empty and "val_loss" in steps.columns:
        final_val = steps.dropna(subset=["val_loss"]).groupby("residual_mode", as_index=False).tail(1)
        final_val_per_mode = final_val.groupby("residual_mode", as_index=False)["val_loss"].last()
        agg = final_val_per_mode.set_index("residual_mode")
    else:
        return []

    rows = []
    for variant, base in VARIANT_TO_BASE.items():
        if variant not in agg.index or base not in agg.index:
            continue
        var_loss = agg.loc[variant, "val_loss"] if "val_loss" in agg.columns else None
        base_loss = agg.loc[base, "val_loss"] if "val_loss" in agg.columns else None
        if var_loss is None or base_loss is None or pd.isna(var_loss) or pd.isna(base_loss):
            continue
        delta = float(var_loss) - float(base_loss)
        rows.append(
            {
                "variant": variant,
                "base": base,
                "val_loss_variant": round(float(var_loss), 4),
                "val_loss_base": round(float(base_loss), 4),
                "delta_val_loss": round(delta, 4),
                "ppl_variant": _to_ppl(var_loss),
                "ppl_base": _to_ppl(base_loss),
            }
        )
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--csv", type=Path, required=True, help="ablation_summary.csv")
    parser.add_argument("--steps-csv", type=Path, default=None, help="ablation_steps.csv (optional)")
    parser.add_argument("--out", type=Path, required=True, help="Output SUMMARY.md")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    df = pd.read_csv(args.csv)
    steps = pd.read_csv(args.steps_csv) if args.steps_csv and args.steps_csv.is_file() else None
    rows = build_rows(df, steps)
    if not rows:
        log.error("No rows in %s (or no val_loss in steps)", args.csv)
        return 1

    # Bold the smallest delta (best - most "removing X hurts least" or "improves").
    rows = bold_winner(rows, "delta_val_loss", lower_is_better=True)
    rows = apply_bold(rows, ["delta_val_loss"])

    headers: dict[str, str] = {
        "variant": "Ablation variant",
        "base": "vs base mode",
        "val_loss_variant": "val_loss (variant)",
        "val_loss_base": "val_loss (base)",
        "delta_val_loss": "Δ val_loss ↓",
        "ppl_variant": "PPL (variant)",
        "ppl_base": "PPL (base)",
    }
    headers = {k: v for k, v in headers.items() if k in rows[0]}

    write_markdown_table(
        args.out,
        title="Ablation Summary",
        rows=rows,
        headers=headers,
        caption="Δ validation loss when removing each component vs the full mode. Bold = best (smallest Δ).",
        floatfmt=".4f",
        preamble="Generated by `python -m scripts.tables.ablation_table`.\n\nVariant definitions:\n"
        "- **vega_no_var_reg**: VEGA with the variance regularizer weight set to 0.\n"
        "- **vega_no_multiscale**: VEGA with all fast/slow decay ranges clamped to [2.0, 2.0].\n"
        "- **rr_no_depth_biases**: Recurrent Residual with the 4 depth-bias parameters zeroed and frozen.",
    )
    log.info("Wrote %s", args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
