"""Depth Preservation Score (DPS) summary table.

Reads ``results/aggregate/depth_preservation.csv`` and emits
``results/depth_preservation/SUMMARY.md`` with one row per mode and
columns for DRI, GPI, mean DPS, mean GPS, n_tokens, n_layers.  The
"winning" mode (highest DRI) is bolded.

Usage:
    python -m scripts.tables.dps_table \\
        --csv results/aggregate/depth_preservation.csv \\
        --out results/depth_preservation/SUMMARY.md
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

from scripts.tables.format import (
    apply_bold,
    bold_winner,
    write_markdown_table,
)

log = logging.getLogger(__name__)


def build_rows(df: pd.DataFrame) -> list[dict]:
    """Aggregate the DPS CSV to one row per residual mode (mean across runs)."""
    if df.empty:
        return []
    cols = [c for c in ("dri", "gpi", "n_tokens", "n_layers", "dps_mean", "gps_mean", "dps_min", "dps_max") if c in df.columns]
    agg = df.groupby("residual_mode", as_index=False)[cols].mean(numeric_only=True)
    # Round for readability.
    for col in ("dri", "gpi", "dps_mean", "gps_mean", "dps_min", "dps_max"):
        if col in agg.columns:
            agg[col] = agg[col].round(4)
    if "n_tokens" in agg.columns:
        agg["n_tokens"] = agg["n_tokens"].astype("Int64")
    if "n_layers" in agg.columns:
        agg["n_layers"] = agg["n_layers"].astype("Int64")
    agg = agg.sort_values("dri", ascending=False) if "dri" in agg.columns else agg
    return agg.to_dict("records")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--csv", type=Path, required=True, help="depth_preservation.csv")
    parser.add_argument("--out", type=Path, required=True, help="Output SUMMARY.md")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    df = pd.read_csv(args.csv)
    rows = build_rows(df)
    if not rows:
        log.error("No rows in %s", args.csv)
        return 1

    # Bold the winner (highest DRI).
    rows = bold_winner(rows, "dri", lower_is_better=False)
    rows = apply_bold(rows, ["dri", "gpi", "dps_mean", "gps_mean"])

    headers: dict[str, str] = {
        "residual_mode": "Mode",
        "dri": "DRI ↑",
        "gpi": "GPI ↑",
        "dps_mean": "DPS̄ (mean)",
        "gps_mean": "GPS̄ (mean)",
        "dps_min": "DPS min",
        "n_tokens": "n_tokens",
        "n_layers": "n_layers",
    }
    headers = {k: v for k, v in headers.items() if k in rows[0]}

    write_markdown_table(
        args.out,
        title="Depth Preservation Summary",
        rows=rows,
        headers=headers,
        caption="Per-mode DRI, GPI, and DPS statistics (averaged across runs). Bold = best DRI.",
        floatfmt=".4f",
        preamble="Generated by `python -m scripts.tables.dps_table`. See plots/depth_preservation/ for per-layer curves.",
    )
    log.info("Wrote %s", args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
