"""Iso-FLOP summary table: wide-shallow vs narrow-deep val loss per mode.

Reads ``results/aggregate/iso_flop_summary.csv`` (and optionally
``iso_flop_steps.csv``) and emits ``results/iso_flop/SUMMARY.md``.

For each mode, the iso-FLOP comparison has a "wide_shallow" and
"narrow_deep" variant.  This table shows their val_loss, params, and
estimated FLOPs side by side.

Usage:
    python -m scripts.tables.iso_flop_table \\
        --csv results/aggregate/iso_flop_summary.csv \\
        --steps-csv results/aggregate/iso_flop_steps.csv \\
        --out results/iso_flop/SUMMARY.md
"""

from __future__ import annotations

import argparse
import logging
import math
import sys
from pathlib import Path

import pandas as pd

from scripts.tables.format import (
    apply_bold,
    bold_winner,
    write_markdown_table,
)

log = logging.getLogger(__name__)


def build_rows(df: pd.DataFrame, steps: pd.DataFrame | None) -> list[dict]:
    if df.empty:
        return []
    # Extract final val_loss per (mode, run) from steps.
    if steps is not None and not steps.empty and "val_loss" in steps.columns:
        final_val = steps.dropna(subset=["val_loss"]).groupby("run_id", as_index=False).tail(1)
        final_val = final_val[["run_id", "val_loss"]]
        df = df.merge(final_val, on="run_id", how="left")
    if "parameter_count" in df.columns:
        df["estimated_flops"] = (df["parameter_count"] * 6).astype("Int64")
    rows = []
    for _, r in df.iterrows():
        val_loss = r.get("val_loss")
        rows.append({
            "residual_mode": r.get("residual_mode", "?"),
            "shape": "wide-shallow" if "wide_shallow" in str(r.get("residual_mode", "")) else "narrow-deep" if "narrow_deep" in str(r.get("residual_mode", "")) else "—",
            "val_loss": round(float(val_loss), 4) if val_loss is not None and not pd.isna(val_loss) else None,
            "val_ppl": round(math.exp(min(float(val_loss), 20.0)), 2) if val_loss is not None and not pd.isna(val_loss) else None,
            "parameter_count": int(r["parameter_count"]) if pd.notna(r.get("parameter_count")) else None,
            "estimated_flops": int(r["estimated_flops"]) if pd.notna(r.get("estimated_flops")) else None,
            "elapsed_seconds": round(float(r["elapsed_seconds"]), 2) if pd.notna(r.get("elapsed_seconds")) else None,
        })
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--csv", type=Path, required=True, help="iso_flop_summary.csv")
    parser.add_argument("--steps-csv", type=Path, default=None, help="iso_flop_steps.csv (optional)")
    parser.add_argument("--out", type=Path, required=True, help="Output SUMMARY.md")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    df = pd.read_csv(args.csv)
    steps = pd.read_csv(args.steps_csv) if args.steps_csv and args.steps_csv.is_file() else None
    rows = build_rows(df, steps)
    if not rows:
        log.error("No rows in %s", args.csv)
        return 1

    # Bold winner.
    rows = bold_winner(rows, "val_loss", lower_is_better=True)
    rows = apply_bold(rows, ["val_loss", "val_ppl"])

    headers: dict[str, str] = {
        "residual_mode": "Mode",
        "shape": "Shape",
        "val_loss": "val_loss (nats) ↓",
        "val_ppl": "val_ppl ↓",
        "parameter_count": "params",
        "estimated_flops": "est. FLOPs (proxy)",
        "elapsed_seconds": "elapsed (s)",
    }
    headers = {k: v for k, v in headers.items() if k in rows[0]}

    write_markdown_table(
        args.out,
        title="Iso-FLOP Summary",
        rows=rows,
        headers=headers,
        caption="Per-(mode, shape) validation loss at matched parameter count. Bold = lowest val_loss.",
        floatfmt=".4f",
        preamble="Generated by `python -m scripts.tables.iso_flop_table`.\n\n"
                 "Wide-shallow variants use 6 layers × 1024 d_model; narrow-deep use 24 layers × 512 d_model. "
                 "FLOPs are estimated as 6 × params (a consistent proxy, not a true FLOP count).",
    )
    log.info("Wrote %s", args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
