"""LM quality summary table: val_ppl, throughput, peak_mem, params per mode.

Reads ``results/aggregate/lm_quality_summary.csv`` and emits
``results/lm_quality/SUMMARY.md``.  The best (lowest) val_loss and best
(highest) throughput are bolded.

Usage:
    python -m scripts.tables.lm_quality_table \\
        --csv results/aggregate/lm_quality_summary.csv \\
        --steps-csv results/aggregate/lm_quality_steps.csv \\
        --out results/lm_quality/SUMMARY.md
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

from scripts.tables.format import (
    apply_bold,
    bold_winner,
    write_markdown_table,
)

log = logging.getLogger(__name__)


def build_rows(df: pd.DataFrame, steps: pd.DataFrame | None) -> list[dict]:
    if df.empty:
        return []
    # Aggregate per mode: mean across runs.
    agg_cols = [c for c in ("parameter_count", "elapsed_seconds", "global_step", "peak_cuda_memory_mb") if c in df.columns]
    agg = df.groupby("residual_mode", as_index=False)[agg_cols].mean(numeric_only=True)
    # If we have steps, extract mean throughput and final val_loss.
    if steps is not None and not steps.empty and "tokens_per_second" in steps.columns:
        throughput = steps.dropna(subset=["tokens_per_second"]).groupby("residual_mode", as_index=False)["tokens_per_second"].mean()
        agg = agg.merge(throughput, on="residual_mode", how="left")
    if steps is not None and not steps.empty and "val_loss" in steps.columns:
        final_val = steps.dropna(subset=["val_loss"]).groupby("residual_mode", as_index=False).tail(1)
        # Use the LAST val_loss per mode.
        final_val_per_mode = final_val.groupby("residual_mode", as_index=False)["val_loss"].last()
        agg = agg.merge(final_val_per_mode, on="residual_mode", how="left")
        if "val_loss" in agg.columns:
            agg["val_ppl"] = (agg["val_loss"].apply(lambda x: float(x) if x is not None else None)).apply(
                lambda x: round(__import__("math").exp(min(x, 20.0)), 2) if x is not None else None
            )

    # Format.
    for col in ("peak_cuda_memory_mb", "elapsed_seconds", "tokens_per_second", "val_loss"):
        if col in agg.columns:
            agg[col] = agg[col].round(2)
    for col in ("parameter_count", "global_step"):
        if col in agg.columns:
            agg[col] = agg[col].astype("Int64")
    if "val_loss" in agg.columns:
        agg = agg.sort_values("val_loss", ascending=True)
    return agg.to_dict("records")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--csv", type=Path, required=True, help="lm_quality_summary.csv")
    parser.add_argument("--steps-csv", type=Path, default=None, help="lm_quality_steps.csv (optional)")
    parser.add_argument("--out", type=Path, required=True, help="Output SUMMARY.md")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    df = pd.read_csv(args.csv)
    steps = pd.read_csv(args.steps_csv) if args.steps_csv and args.steps_csv.is_file() else None
    rows = build_rows(df, steps)
    if not rows:
        log.error("No rows in %s", args.csv)
        return 1

    # Bold winners.
    if "val_loss" in rows[0]:
        rows = bold_winner(rows, "val_loss", lower_is_better=True)
    if "tokens_per_second" in rows[0]:
        rows = bold_winner(rows, "tokens_per_second", lower_is_better=False)
    rows = apply_bold(rows, ["val_loss", "val_ppl", "tokens_per_second", "peak_cuda_memory_mb", "parameter_count"])

    headers: dict[str, str] = {
        "residual_mode": "Mode",
        "val_loss": "val_loss (nats) ↓",
        "val_ppl": "val_ppl ↓",
        "tokens_per_second": "tok/s ↑",
        "parameter_count": "params",
        "elapsed_seconds": "elapsed (s)",
        "peak_cuda_memory_mb": "peak_mem (MiB)",
    }
    headers = {k: v for k, v in headers.items() if k in rows[0]}

    write_markdown_table(
        args.out,
        title="LM Quality Summary",
        rows=rows,
        headers=headers,
        caption="Per-mode validation loss / perplexity, throughput, and memory. Bold = best in column.",
        floatfmt=".2f",
        preamble="Generated by `python -m scripts.tables.lm_quality_table`. See plots/lm_quality/ for loss curves and gradient norms.",
    )
    log.info("Wrote %s", args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
