"""Natural NIAH (Needle in a Haystack) summary table: passkey accuracy per mode.

Reads ``results/aggregate/natural_niah.csv`` and emits
``results/natural_niah/SUMMARY.md``.  For each (mode, run_id) pair, shows
the passkey-retrieval success as a ✓ or ✗.

Usage:
    python -m scripts.tables.niah_table \\
        --csv results/aggregate/natural_niah.csv \\
        --out results/natural_niah/SUMMARY.md
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

from scripts.tables.format import write_markdown_table

log = logging.getLogger(__name__)


def build_rows(df: pd.DataFrame) -> list[dict]:
    if df.empty:
        return []
    rows = []
    for _, r in df.iterrows():
        gen_text = r.get("generated_text", "")
        if not isinstance(gen_text, str):
            gen_text = str(gen_text) if gen_text is not None else ""
        rows.append({
            "residual_mode": r.get("residual_mode", "?"),
            "run_id": r.get("run_id", "?"),
            "input_length": r.get("input_length"),
            "success": "✓" if r.get("success") else "✗",
            "generated_text": gen_text[:80],
        })
    rows = sorted(rows, key=lambda r: (str(r["residual_mode"]), str(r["run_id"])))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--csv", type=Path, required=True, help="natural_niah.csv")
    parser.add_argument("--out", type=Path, required=True, help="Output SUMMARY.md")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    df = pd.read_csv(args.csv)
    rows = build_rows(df)
    if not rows:
        log.error("No rows in %s", args.csv)
        return 1

    headers: dict[str, str] = {
        "residual_mode": "Mode",
        "run_id": "Run",
        "input_length": "input length (tok)",
        "success": "Passkey retrieved?",
        "generated_text": "Generated completion (truncated)",
    }
    headers = {k: v for k, v in headers.items() if k in rows[0]}

    write_markdown_table(
        args.out,
        title="Natural-Text Needle-in-a-Haystack Summary",
        rows=rows,
        headers=headers,
        caption="Per-mode passkey retrieval: ✓ = success, ✗ = failure. The passkey '84729' is injected at the 20% mark of a long natural text.",
        preamble="Generated by `python -m scripts.tables.niah_table`.\n\n"
                 "Each run loads a checkpoint from `lm_quality/<mode>/<run_id>/checkpoints/` and autoregressively "
                 "generates 5 tokens; success is `True` iff the substring '84729' appears in the generated text.",
    )
    log.info("Wrote %s", args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
